### ISSUE TITLE
The Masked is pathfinder Caton

### ISSUE THREAD

**Issue by AlanCratys** [VirusTLNR/LethalIntelligence#6]
The masked often lags in searching for a path and gets stuck and difficult to move while watching the player on the spaceship. It usually tries to move towards the player but gets stuck in place and trembles slightly

**Comment by VirusTLNR** [comment]
hi, this is kind of intended.

Stealthy when confronted with a player, is supposed to run away, instead, currently right now, they keep their distance, but do not run away, this is the "quivering" i think you refer to.

If you have a log of the next time this occurs, then send me the full log (with debug mode turned on in the LI settings), then I can confirm it. The only known example of a masked getting stuck on pathing is routing to the breaker box, and this is an issue with the breaker box being buried behind a wall where the masked cannot reach. I am looking to resolve this issue, and I am looking to change how Stealthy behaves, as I realise it looks weird, and I think it also makes players lose FPS.
